# Generated by Django 3.2.4 on 2021-06-30 13:31

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=255)),
                ('stud_image', models.ImageField(null=True, upload_to=student.models.stud.update_filename)),
            ],
        ),
    ]
